### ISSUE TITLE
Error: "Mapbox tile optimization failed TypeError: Cannot read properties of undefined (reading 'other:composite')" when using Maplibre

### ISSUE THREAD

**Issue by bruesba** [ted-piotrowski/mapbox-gl-shadow-simulator#11]
I'm implementing the package in my Maplibre project in order to display the shadows of buildings in a custom vector tile source.

My code is as follows (as per the documentation): 

```typescript
      this.maplibreMap.on('load', () => {
        const shadeMap = new ShadeMap({
          date: new Date(),    // display shadows for current date
          color: '#01112f',    // shade color
          opacity: 0.7,        // opacity of shade color
          apiKey: <KEY>,    // obtain from https://shademap.app/about/
          getFeatures: async () => {
            await mapLoaded(this.maplibreMap);
            const buildingData = this.maplibreMap.querySourceFeatures('pand_geometry', { sourceLayer: 'pand_geometry' }).filter((feature) => {
              return feature.properties && feature.properties.height
            });
            return buildingData as any;
          },
          debug: (msg) => { console.log(new Date().toISOString(), msg) },
        }).addTo(this.maplibreMap as any);
      
        // advance shade by 1 hour
        shadeMap.setDate(new Date(Date.now() + 1000 * 60 * 60)); 
      });
```

When looking around in my Maplibre map, the following error appears:

![image](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/47451532/478b0bf2-ca27-4980-8235-d7e921c20c8a)

Which makes sense because `const r = this._map.style._sourceCaches["other:composite"]...` as found in mapbox-gl-shadow-simulator.umd.min.js, doesn't point to an existing property. `Map.style.sourceCaches` is a valid property, however.

Furthermore, do I understand correctly that I need to name my vector tile source 'other:composite' since it is hardcoded in the package? I'd rather keep the name I'd given it; 'pand_geometry'.

I'm using the latest Maplibre version: 3.6.2.

Furthermore, no shadows are displayed with my implementation. Might be unrelated of course. But does it seem like anything is missing in my code?

**Comment by ted-piotrowski** [comment]
Thanks for catching this.

The exception you see is unrelated to the building models. It deals with calculating what elevation tiles to load when the map is tilted more than 45 degrees. In previous versions of the shadow simulator you were unable to tilt the map more than 45 degrees because it could not deal with an infinite horizon.

Are you testing with the map tilted? Can you confirm that your shadows display correctly when the map is not tilted or tilted less than 45 degrees?

I will add an example to the repo using Maplibre and try to fix this issue in the meantime.

**Comment by bruesba** [comment]
Thanks for responding!

I _was_ testing with the map tilted. Can't confirm right now that that is when the error showed up, but it came up intermittently, so it could well have been whilst tilting.

I couldn't get the shadows to work at all. The code pasted above is my ShadeMap implementation. I'm using custom, locally hosted vector tiles. Fill extrustion using Maplibre works on the tiles. Any idea as to what could be wrong? What else would you need from me for debugging?

**Comment by ted-piotrowski** [comment]
I've added a maplibre example to the repository: https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/blob/aebcfa4db26ed1e04dbc9364335bac0f82cdb199/examples/maplibre.html

Here is an example of mountain shadows. The way your code is currently configured, there is no terrainSource so you will not see terrain shadows unless you add it: https://ted-piotrowski.github.io/mapbox-gl-shadow-simulator/examples/maplibre.html#8/47.667/-121.895

Here you can see the building shadows, however, the free maplibre vector tile set does not include buildings layer so I am instead fetching buildings from OSM overpass api. But hopefully you can see what the getFeatures() method should return and modify to fetch the buildings from your data layer: https://ted-piotrowski.github.io/mapbox-gl-shadow-simulator/examples/maplibre.html#16.49/47.613423/-122.303274

I hope this helps you debug your issue. Let me know if you succeed or need more help.

**Comment by bruesba** [comment]
Thank you, Ted! The shadows are working now. 

I do have another question: the shadow layer is sometimes visible where it shouldn't with 3d buildings. See the screengrab below: the shadows at the top of the building are at the base of the building at ground level and should not be visible.
![image](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/47451532/38b8cf6c-da4a-4328-9b6d-bb8d594f0069)

This happens both when I add the shade map as shown in your documentation (using `shadeMap.addTo(this.maplibreMap)`), and when I add them with the `beforeId` option of the map's addLayer() method: `this.maplibreMap.addLayer(shadeMap as any, 'pand_geometry_fill');`. The 3d building layer has paint style `'fill-extrusion-opacity': 1`.  Is there a way to display the shadows less confusingly with 3d buildings?

**Comment by ted-piotrowski** [comment]
@bruesba My guess is you are using 'pand_geometry_fill' as a source for a 'fill-extrusion' layer. Assuming your 'fill-extrusion' layer name is '3d-buildings', you should be able to set the 3d buildings as the top-most layer (above the shadow layer) with the following code:

```
map.moveLayer('3d-buildings');
```

Does that work for you?

**Comment by bruesba** [comment]
@ted-piotrowski Your method for changing a drawing order works. But I think my problem statement was inaccurate. My problem is that shadows from the base of a building are visible through the fill extrusion layer.

![image](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/47451532/a6d2e17b-98eb-43f7-9fcf-3c982bc7fe00)
In the above example you can see the dark shadows starting at the base of the other side of the building _through_ the roof of the building. I think ideally, the street-level shadows behind a building should not be visible on top of/through the building. So what's marked in yellow below, should be invisible.

![image](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/47451532/30f0d75f-7eb1-4d6d-a8b2-2697cc3d7ae9)
Is that possible with ShadeMap? Please let me know if I'm misunderstanding anything.

**Comment by ted-piotrowski** [comment]
What is the opacity level of your extrusion layer? Does the problem go away
if opacity is set to 1?

**Comment by ted-piotrowski** [comment]
In the first image you see the shadow layer as the top most layer. This means once the map, streets, buildings, etc are rendered, the shadow layer will be painted over the top:

![before](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/2023571/d74c83b3-7af4-4859-8110-04fe8abeab27)

Next is after calling `map.moveLayer('3d-buildings')` which moves the `3d-buildings` extruded layer above the shadow layer so any shadows that are behind the buildings are covered by the buildings themselves:

![after](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/2023571/bd244346-d940-4918-ac56-d3ebc82eb9ac)

I modified this example on the Maplibre website: https://maplibre.org/maplibre-gl-js/docs/examples/3d-buildings/

**Comment by bruesba** [comment]
Fill-extrusion-opacity is set to 1. See the code below. 'pand_perceel_geometry' is a vector tile source.
```
        {
          'id': 'pand_geometry_fill',
          'type': 'fill-extrusion',
          'source': 'pand_perceel_geometry',
          'source-layer': 'pand_geometry',
          'layout': {
            visibility: 'visible',
          },
          'paint': {
            'fill-extrusion-color': [
              'interpolate',
              ['linear'],
              ['get', 'height'], 0, 'lightgrey', 20, 'gray', 40, 'dimgrey'
            ],
            'fill-extrusion-height': [
              'interpolate',
              ['linear'],
              ['zoom'],
              15,
              0,
              16,
              ['get', 'height']
            ],
            'fill-extrusion-base': ['case',
              ['>=', ['get', 'zoom'], 16],
              ['get', 'b3_h_maaiveld'], 0
            ],
            'fill-extrusion-opacity': 1
          }
        },
```
This behaviour occurs when I don't set `this.maplibreMap.moveLayer('pand_geometry_fill')`. When I do reset the 3d layer draw index, shadows are not drawn on buildings at all (which is to be expected, but not what I wish to happen).
Another example of the shades on top of buildings:
![image](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/47451532/a65f560b-1081-4d1f-9539-6999430057dc)

And with the buildings moved on top of the shademap:
![image](https://github.com/ted-piotrowski/mapbox-gl-shadow-simulator/assets/47451532/776e153f-e140-446d-a043-a27e631ae9df)

**Comment by bruesba** [comment]
Pardon me, hadn't seen your message. I said the same thing so at least I'm understanding you right!

Ideally, I'd like to see shadows on top and on the sides of lower buildings! But I imagine that's a very difficult wish. Anyway, thanks for your help!

**Comment by ted-piotrowski** [comment]
> Ideally, I'd like to see shadows on top and on the sides of lower buildings! But I imagine that's a very difficult wish. Anyway, thanks for your help!

This is something I am working ([some experiments](https://github.com/ted-piotrowski/mapbox-gl-building-shadows)) on but it will take a little more time. I will get in touch when it's reading for testing.

Is it okay if I close this issue as resolved at this point?
