### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by SvanteRichter** [ted-piotrowski/mapbox-gl-shadow-simulator#13]
Hello!

The package.json says `"license": "UNLICENSED"` and there is no license file. Does that mean that this package is not under any open-source license and I'm not allowed to use it?

Thanks!

**Comment by ted-piotrowski** [comment]
I allow free usage for academic and non-commercial projects. For commercial
usage I charge an annual fee per domain/app.

See https://shademap.app/about

Email me if you're not sure what your project falls under.
