### ISSUE TITLE
React Example

### ISSUE THREAD

**Issue by pedertanberg** [ted-piotrowski/mapbox-gl-shadow-simulator#2]
Could you upload a React.js example? Would be highly appreciated.

**Comment by ted-piotrowski** [comment]
Hi Peder, I can provide a react example. Could you tell me more about your React setup. Are you using a library like react-map-gl or using Mapbox's guide for using Mapbox with React (https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/) ?

**Comment by pedertanberg** [comment]
Hi Ted, 

Thanks a lot, really appreciate it! 

(https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/) is more than enough to get started with.
