### ISSUE TITLE
GeoTIFFs all download as shademap.tiff

### ISSUE THREAD

**Issue by twest820** [ted-piotrowski/mapbox-gl-shadow-simulator#8]
Hi Ted, I just had a bit of time to do the download a sun exposure raster for every month of the year which we discussed a bit ago. Since there are 12 months, that means I get 12 files which Chrome and Windows helpfully decide to name

- shademap.tiff
- shademap (1).tiff
- shademap (2).tiff
- shademap (3).tiff
- shademap (4).tiff
- shademap (5).tiff
- shademap (6).tiff
- shademap (7).tiff
- shademap (8).tiff
- shademap (9).tiff
- shademap (10).tiff
- shademap (11).tiff

Since I downloaded them in order from January to December it's not a big deal to rename shademap.tiff to sun exposure 2023-01.tiff, shademap (1).tiff to sun exposure 2023-02.tiff, and so on.

However, since ShadeMap already knows the data type and date it's exporting it seems kind of silly to do this manually.  So, for user friendliness, it'd be nice if the downloaded file names defaulted to something like

- "shademap YYYY-MM-ddThh.mmzzz.tiff"
- "sun exposure YYYY-MM-dd.tiff"

I can see arguments for also including the start and end times for part of day sun exposures and location info (besides the timezone).

**Comment by ted-piotrowski** [comment]
Great idea. I just deployed this change. The format is now:

```
shade_YYYY-MM-ddThh.mm.ss.zzz.tiff
sun_exposure_YYYY-MM-dd.tiff
```
